version: '3'
services:
  web:
    build:
      context: . 
      dockerfile: DockerFile
    image: node-web-app
    container_name: node-web-app
    env_file: .env
    volumes:
      - .:/usr/app/
      # - node_modules:/usr/app/node_modules
    networks:
      - app-network     
    ports:
      - "5000:5000"
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:  